/:
  controller: LayoutController
  action: index

/api/memu/index:
  controller: DashboardController
  action: index

/admin/dashboard/index:
  controller: DashboardController
  action: index

/admin/user/index:
  controller: UserController
  action: index

/admin/user/insert:
  controller: UserController
  action: insert

/admin/user/update:
  controller: UserController
  action: update

/admin/user/delete:
  controller: UserController
  action: delete

/admin/user/status:
  controller: UserController
  action: status

/admin/user/changepassword:
  controller: UserController
  action: changepassword

/admin/category/index:
  controller: CategoryController
  action: index

/admin/category/insert:
  controller: CategoryController
  action: insert

/admin/category/update:
  controller: CategoryController
  action: update

/admin/category/delete:
  controller: CategoryController
  action: delete

/admin/category/status:
  controller: CategoryController
  action: status

/admin/category/sort:
  controller: CategoryController
  action: sort

/admin/post/index:
  controller: PostController
  action: index

/admin/post/insert:
  controller: PostController
  action: insert

/admin/post/update:
  controller: PostController
  action: update

/admin/post/delete:
  controller: PostController
  action: delete

/admin/post/status:
  controller: PostController
  action: status

/admin/menu/index:
  controller: MenuController
  action: index

/admin/menu/insert:
  controller: MenuController
  action: insert

/admin/menu/update:
  controller: MenuController
  action: update

/admin/menu/delete:
  controller: MenuController
  action: delete

/admin/menu/status:
  controller: MenuController
  action: status

/admin/menu/sort:
  controller: MenuController
  action: sort

/admin/comment/index:
  controller: CommentController
  action: index

/admin/comment/insert:
  controller: CommentController
  action: insert

/admin/comment/update:
  controller: CommentController
  action: update

/admin/comment/delete:
  controller: CommentController
  action: delete

/admin/comment/status:
  controller: CommentController
  action: status

/login:
  controller: SecurityController
  action: login

/processlogin:
  controller: SecurityController
  action: processlogin

/logout:
  controller: SecurityController
  action: logout

/admin/user/active:
  controller: SecurityController
  action: active
